ViewModels/Shared/HeaderSectionViewModel.cs
// -----------------------------------------------------------------------
//   Copyright (C) 2018 Adam Hancock
//    
//   SectionViewModel.cs can not be copied and/or distributed without the express
//   permission of Adam Hancock
// -----------------------------------------------------------------------

namespace FlowerFest.ViewModels.Shared
{
    public class HeaderSectionViewModel
    {
        public string Tag { get; set; }
    }
}

ViewModels/Shared/SectionViewModel.cs
// -----------------------------------------------------------------------
//   Copyright (C) 2018 Adam Hancock
//    
//   SectionViewModel.cs can not be copied and/or distributed without the express
//   permission of Adam Hancock
// -----------------------------------------------------------------------

namespace FlowerFest.ViewModels.Shared
{
    public class HeaderSectionViewModel
    {
        public string Tag { get; set; }
    }
}

Controllers/FilesController.cs
// -----------------------------------------------------------------------
//   Copyright (C) 2018 Adam Hancock
//    
//   FilesController.cs can not be copied and/or distributed without the express
//   permission of Adam Hancock
// -----------------------------------------------------------------------

namespace FlowerFest.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using AutoMapper;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;
    using Services.Interfaces;
    using ViewModels;

    [Route("Dashboard/Files")]
    public class FilesController : BaseController<FilesController>
    {
        private readonly IFileService _fileService;
        private readonly IMapper _mapper;

        public FilesController(
            IFileService fileService,
            IMapper mapper,
            ILogger<FilesController> logger)
            : base(logger)
        {
            _fileService = fileService;
            _mapper = mapper;
        }

        [HttpPost]
        [Authorize]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Upload(IFormFile file)
        {
            try
            {
                await _fileService.Save(file);

                return RedirectToAction("Index");
            }
            catch (NotSupportedException e)
            {
                return BadRequest();
            }
            catch (Exception e)
            {
                return ServerError(e);
            }
        }

        [Route("{id}")]
        [Authorize]
        public async Task<IActionResult> Index(string id)
        {
            try
            {
                if (!string.IsNullOrEmpty(id))
                {
                    var file = await _fileService.GetFile(Guid.Parse(id));

                    if (file != null)
                    {
                        var data = await _fileService.Read(file);
                        var type = await _fileService.GetContentType(file);

                        return File(data, type, id);
                    }

                    return NotFound();
                }

                return View("Index", _mapper.Map<IEnumerable<FileDetailsViewModel>>(
                    await _fileService.GetFiles()));
            }
            catch (Exception e)
            {
                return ServerError(e);
            }
        }
        
        [HttpPost]
        [Authorize]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Delete(string id)
        {
            try
            {
                if (await _fileService.Delete(Guid.Parse(id)))
                {
                    return Ok();
                }

                return NotFound();
            }
            catch (Exception e)
            {
                return ServerError(e);
            }
        }
    }
}

Views/Shared/_DashboardLayout.cshtml
@inject IOptionsSnapshot<BlogSettings> settings
@{
    var host = Context.Request.Scheme + "://" + Context.Request.Host;
}
<!DOCTYPE html>
<html lang="en">
<head prefix="og: http://ogp.me/ns#">

    <meta charset="utf-8"/>
    <title>@ViewData["Title"]</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1"/>
    <meta name="description" content="@ViewData["Description"]"/>

    @*<environment include="Development">
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="~/lib/bootstrap.min.css" />
        </environment>*@

    <!-- Styles -->
    <link rel="stylesheet" href="~/lib/font-awesome.css" type="text/css"/>
    <link rel="stylesheet" href="~/lib/hamburgers.css" type="text/css"/>
    <link rel="stylesheet" href="~/lib/bootstrap.css" type="text/css"/>
    <link rel="stylesheet" href="~/lib/animate.css" type="text/css"/>

    <link rel="stylesheet" href="~/css/et-line.css" type="text/css"/>
    <link rel="stylesheet" href="~/css/site.css" type="text/css"/>

    <link rel="stylesheet" href="~/lib/jarallax.css" type="text/css"/>

    @RenderSection("Styles", false)

    <meta property="og:type" content="website"/>
    <meta property="og:title" content="@ViewData["Title"]"/>
    <meta property="og:description" content="@ViewData["Description"]"/>
    <meta property="og:url" content="@(host + Context.Request.Path)"/>
    <meta property="og:image" content="@host/img/icon180x180.png"/>
    <meta property="og:image:width" content="180"/>
    <meta property="og:image:height" content="180"/>

    <link rel="icon" type="image/png" sizes="16x16" href="/img/icon16x16.png"/>
    <link rel="apple-touch-icon" sizes="180x180" href="~/img/icon180x180.png"/>
    <link rel="shortcut icon" href="/img/icon16x16.png"/>

    <meta name="msapplication-square150x150logo" content="/img/icon180x180.png"/>
    <link rel="edituri" type="application/rsd+xml" title="RSD" href="~/rsd.xml"/>

    <link rel="alternate" type="application/rss+xml" href="~/feed/rss/"/>
    <link rel="alternate" type="application/atom+xml" href="~/feed/atom/"/>

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"/>

</head>

<body itemscope itemtype="http://schema.org/WebPage" class="wow-animate">

<!-- Site preloader -->
<section id="spinner">
    <div class="site-spinner"></div>
</section>
<!-- End Site preloader -->

<div id="dashboard" class="wrapper">

    <!-- Sidebar -->
    <nav id="sidebar">

        <div class="sidebar-header">
            <h3>Dashboard</h3>
        </div>

        <!-- Sidebar Links -->
        <ul class="list-unstyled components">
            <li class="active">
                <a asp-controller="Files" asp-action="Index">Files</a>
            </li>
            
        </ul>
    </nav>

    <!-- Page Content -->
    <div id="content">

        @RenderBody()

    </div>

</div>

<!-- JS Script -->
<script src="~/lib/jquery.js"></script>
<script src="~/lib/jquery.validate.js"></script>
<script src="~/lib/bootstrap.js"></script>
<script src="~/lib/smoothscroll.js"></script>

<script src="~/js/site.js" type="text/javascript"></script>


@RenderSection("Scripts", false)

</body>


</html>

Views/Shared/_Header.cshtml
<div class="header-inner">

    <!-- Logo -->
    <div class="logo">
        <a asp-controller="Home" asp-action="Index">
            <img src="~/img/logo-large.png"/>
        </a>
    </div>
    <!-- End Logo -->

    <!-- Mobile Navbar Icon -->
    <div class="nav-mobile nav-bar-icon">
        <span></span>
    </div>
    <!-- End Mobile Navbar Icon -->

    <!-- Navbar Navigation -->
    <div class="nav-menu singlepage-nav">
        <ul class="nav-menu-inner">
            <li>
                <a class="current" href="@Url.Action("Index", "Home", new {area = ""})#intro">Home</a>
            </li>
            
            @foreach (var section in Model.HeaderSections)
            {
                <li>
                    @{
                        var tag = section.Tag;
                        var url = $"{Url.Action("Index", "Home", new { area = "" })}#{tag}";
                    }

                    <a href="@url">@tag</a>
                </li>
            }
            
            <li>
                <a href="@Url.Action("Index", "Home", new {area = ""})#news">News</a>
            </li>

            <li>
                <a asp-controller="Blog" asp-action="Index" asp-area="Blog">Blog</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Home", new {area = ""})#contact">Contact</a>
            </li>

            @*@if (User.Identity.IsAuthenticated)
            {
                <li>
                    <a asp-controller="Account" asp-action="LogOutAsync">Logout</a>
                </li>
            }*@
        </ul>
    </div>
    <!-- End Navbar Navigation -->

</div>

Views/Shared/_LandingLayout.cshtml
@inject IOptionsSnapshot<BlogSettings> settings
@{
    var host = Context.Request.Scheme + "://" + Context.Request.Host;
}
<!DOCTYPE html>
<html lang="en">
<head prefix="og: http://ogp.me/ns#">

    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1" />
    <meta name="description" content="@ViewData["Description"]" />

    @*<environment include="Development">
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="~/lib/bootstrap.min.css" />
        </environment>*@
    
    <!-- Styles -->
    <link rel="stylesheet" href="~/lib/font-awesome.css" type="text/css" />
    <link rel="stylesheet" href="~/lib/hamburgers.css" type="text/css" />
    <link rel="stylesheet" href="~/lib/bootstrap.css" type="text/css" />
    <link rel="stylesheet" href="~/lib/animate.css" type="text/css" />

    <link rel="stylesheet" href="~/css/et-line.css" type="text/css" />
    <link rel="stylesheet" href="~/css/site.css" type="text/css" />

    <link rel="stylesheet" href="~/lib/jarallax.css" type="text/css" />

    @RenderSection("Styles", false)

    <meta property="og:type" content="website" />
    <meta property="og:title" content="@ViewData["Title"]" />
    <meta property="og:description" content="@ViewData["Description"]" />
    <meta property="og:url" content="@(host + Context.Request.Path)" />
    <meta property="og:image" content="@host/img/icon180x180.png" />
    <meta property="og:image:width" content="180" />
    <meta property="og:image:height" content="180" />

    <link rel="icon" type="image/png" sizes="16x16" href="/img/icon16x16.png" />
    <link rel="apple-touch-icon" sizes="180x180" href="~/img/icon180x180.png" />
    <link rel="shortcut icon" href="/img/icon16x16.png" />

    <meta name="msapplication-square150x150logo" content="/img/icon180x180.png" />
    <link rel="edituri" type="application/rsd+xml" title="RSD" href="~/rsd.xml" />

    <link rel="alternate" type="application/rss+xml" href="~/feed/rss/" />
    <link rel="alternate" type="application/atom+xml" href="~/feed/atom/" />

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" />
    
</head>

<body itemscope itemtype="http://schema.org/WebPage" class="wow-animate">

<!-- Site preloader -->
<section id="spinner">
    <div class="site-spinner"></div>
</section>
<!-- End Site preloader -->

<!-- Page Wraper -->
<div id="page-wraper">
    
    @RenderBody()

    <!-- Footer -->
    <footer id="footer" class="footer gray-bg">
        <div class="container text-center">
            

            <ul class="social mb-60">
                <li>
                    <a href="https://www.facebook.com/FlowerFest18/" target="_blank">
                        <i class="fa fa-facebook-square"></i>
                    </a>
                </li>
                <li>
                    <a target="_blank" href="https://www.twitter.com/FlowerFest18/">
                        <i class="fa fa-twitter"></i>
                    </a>
                </li>

                <li>
                    <a href="https://www.instagram.com/flowerfest18/" target="_blank">
                        <i class="fa fa-instagram"></i>
                    </a>
                </li>
            </ul>

            <p>
                The FlowerFest Company Ltd, registered in England and Wales under number 11002524
                <br />
                Registered address 10 Bridge Street Christchurch Dorset BH23 1EF
            </p>

            @{
                var year = DateTime.Now.Year.ToString();

                <p class="copyright">
                    <a class="copy-link scroll-top" href="">&copy; FlowerFest @year</a><br/>
                    All Rights Reserved
                </p>
            }


        </div>
    </footer>

</div>

<!-- JS Script -->
<script src="~/lib/jquery.js"></script>
<script src="~/lib/jquery.validate.js"></script>
<script src="~/lib/bootstrap.js"></script>
<script src="~/lib/smoothscroll.js"></script>
<script src="~/lib/wow.js"></script>
<script src="~/lib/owl.carousel.js"></script>
<script src="~/lib/jarallax-element.js"></script>
<script src="~/lib/jarallax.js"></script>

<script src="~/js/site.js" type="text/javascript"></script>


@RenderSection("Scripts", false)

</body>


</html>

Views/Shared/_Layout.cshtml
@inject IOptionsSnapshot<BlogSettings> settings
@{
    var host = Context.Request.Scheme + "://" + Context.Request.Host;
}
<!DOCTYPE html>
<html lang="en">
<head prefix="og: http://ogp.me/ns#">

    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1" />
    <meta name="description" content="@ViewData["Description"]" />

    @*<environment include="Development">
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="~/lib/bootstrap.min.css" />
        </environment>*@
    
    <!-- Styles -->
    <link rel="stylesheet" href="~/lib/font-awesome.css" type="text/css" />
    <link rel="stylesheet" href="~/lib/hamburgers.css" type="text/css" />
    <link rel="stylesheet" href="~/lib/bootstrap.css" type="text/css" />
    <link rel="stylesheet" href="~/lib/animate.css" type="text/css" />

    <link rel="stylesheet" href="~/css/et-line.css" type="text/css" />
    <link rel="stylesheet" href="~/css/site.css" type="text/css" />

    <link rel="stylesheet" href="~/lib/jarallax.css" type="text/css" />

    @RenderSection("Styles", false)

    <meta property="og:type" content="website" />
    <meta property="og:title" content="@ViewData["Title"]" />
    <meta property="og:description" content="@ViewData["Description"]" />
    <meta property="og:url" content="@(host + Context.Request.Path)" />
    <meta property="og:image" content="@host/img/icon180x180.png" />
    <meta property="og:image:width" content="180" />
    <meta property="og:image:height" content="180" />

    <link rel="icon" type="image/png" sizes="16x16" href="/img/icon16x16.png" />
    <link rel="apple-touch-icon" sizes="180x180" href="~/img/icon180x180.png" />
    <link rel="shortcut icon" href="/img/icon16x16.png" />

    <meta name="msapplication-square150x150logo" content="/img/icon180x180.png" />
    <link rel="edituri" type="application/rsd+xml" title="RSD" href="~/rsd.xml" />

    <link rel="alternate" type="application/rss+xml" href="~/feed/rss/" />
    <link rel="alternate" type="application/atom+xml" href="~/feed/atom/" />

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" />
    
</head>

<body itemscope itemtype="http://schema.org/WebPage" class="wow-animate">

<!-- Site preloader -->
<section id="spinner">
    <div class="site-spinner"></div>
</section>
<!-- End Site preloader -->

<!-- Page Wraper -->
<div id="page-wraper">

    <!-- Header -->
    <header id="header" class="header header-light">
        @{
            await Html.RenderPartialAsync("_Header");
        }
    </header>

    @RenderBody()

    <!-- Footer -->
    <footer id="footer" class="footer gray-bg">
        <div class="container text-center">
            <ul class="social mb-60">
                <li>
                    <a href="https://www.facebook.com/FlowerFest18/" target="_blank">
                        <i class="fa fa-facebook-square"></i>
                    </a>
                </li>
                <li>
                    <a target="_blank" href="https://www.twitter.com/FlowerFest18/">
                        <i class="fa fa-twitter"></i>
                    </a>
                </li>

                <li>
                    <a href="https://www.instagram.com/flowerfest18/" target="_blank">
                        <i class="fa fa-instagram"></i>
                    </a>
                </li>
            </ul>
            
            <p style="margin-top: 50px">
                The FlowerFest Company Ltd, registered in England and Wales under number 11002524
                <br/>
                Registered address 10 Bridge Street Christchurch Dorset BH23 1EF
            </p>

            @{
                var year = DateTime.Now.Year.ToString();

                <p class="copyright">
                    <a class="copy-link scroll-top" href="">&copy; FlowerFest @year</a><br/>
                    All Rights Reserved
                </p>
            }

        </div>
    </footer>

</div>

<!-- JS Script -->
<script src="~/lib/jquery.js"></script>
<script src="~/lib/jquery.validate.js"></script>
<script src="~/lib/bootstrap.js"></script>
<script src="~/lib/smoothscroll.js"></script>
<script src="~/lib/wow.js"></script>
<script src="~/lib/owl.carousel.js"></script>
<script src="~/lib/jarallax-element.js"></script>
<script src="~/lib/jarallax.js"></script>

<script src="~/js/site.js" type="text/javascript"></script>


@RenderSection("Scripts", false)

</body>


</html>

Views/Shared/_LoginLayout.cshtml
@inject IOptionsSnapshot<BlogSettings> settings
@{
    var host = Context.Request.Scheme + "://" + Context.Request.Host;
}
<!DOCTYPE html>
<html lang="en">
<head prefix="og: http://ogp.me/ns#">

    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1" />
    <meta name="description" content="@ViewData["Description"]" />

    @*<environment include="Development">
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="~/lib/bootstrap.min.css" />
        </environment>*@
    
    <!-- Styles -->
    <link rel="stylesheet" href="~/lib/font-awesome.css" type="text/css" />
    <link rel="stylesheet" href="~/lib/hamburgers.css" type="text/css" />
    <link rel="stylesheet" href="~/lib/bootstrap.css" type="text/css" />
    <link rel="stylesheet" href="~/lib/animate.css" type="text/css" />

    <link rel="stylesheet" href="~/css/et-line.css" type="text/css" />
    <link rel="stylesheet" href="~/css/site.css" type="text/css" />

    <link rel="stylesheet" href="~/lib/jarallax.css" type="text/css" />

    @RenderSection("Styles", false)

    <meta property="og:type" content="website" />
    <meta property="og:title" content="@ViewData["Title"]" />
    <meta property="og:description" content="@ViewData["Description"]" />
    <meta property="og:url" content="@(host + Context.Request.Path)" />
    <meta property="og:image" content="@host/img/icon180x180.png" />
    <meta property="og:image:width" content="180" />
    <meta property="og:image:height" content="180" />

    <link rel="icon" type="image/png" sizes="16x16" href="/img/icon16x16.png" />
    <link rel="apple-touch-icon" sizes="180x180" href="~/img/icon180x180.png" />
    <link rel="shortcut icon" href="/img/icon16x16.png" />

    <meta name="msapplication-square150x150logo" content="/img/icon180x180.png" />
    <link rel="edituri" type="application/rsd+xml" title="RSD" href="~/rsd.xml" />

    <link rel="alternate" type="application/rss+xml" href="~/feed/rss/" />
    <link rel="alternate" type="application/atom+xml" href="~/feed/atom/" />

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" />
    
</head>

<body itemscope itemtype="http://schema.org/WebPage" class="wow-animate">

<!-- Site preloader -->
<section id="spinner">
    <div class="site-spinner"></div>
</section>
<!-- End Site preloader -->

<!-- Page Wraper -->
<div id="page-wraper">
    
    @RenderBody()

</div>

<!-- JS Script -->
<script src="~/lib/jquery.js"></script>
<script src="~/lib/jquery.validate.js"></script>
<script src="~/lib/bootstrap.js"></script>
<script src="~/lib/smoothscroll.js"></script>
<script src="~/lib/wow.js"></script>
<script src="~/lib/owl.carousel.js"></script>
<script src="~/lib/jarallax-element.js"></script>
<script src="~/lib/jarallax.js"></script>

<script src="~/js/site.js" type="text/javascript"></script>


@RenderSection("Scripts", false)

</body>


</html>

Views/Shared/_SocialSharing.cshtml
@model string
@{
    string currentUrl = Context.Request.Scheme + "://" + Context.Request.Host + Context.Request.Path;
    string enc = System.Net.WebUtility.UrlEncode(currentUrl);
    string text = System.Net.WebUtility.UrlEncode(Model);
}

<aside class="socialsharing">
    <a href="https://www.facebook.com/sharer/sharer.php?u=@enc" target="_blank" rel="noopener noreferrer nofollow">
        <svg role="img" aria-labelledby="_fb">
            <title id="_fb">Share on Facebook</title>
            <path d="M22.676 0H1.324C.593 0 0 .593 0 1.324v21.352C0 23.408.593 24 1.324 24h11.494v-9.294H9.689v-3.621h3.129V8.41c0-3.099 1.894-4.785 4.659-4.785 1.325 0 2.464.097 2.796.141v3.24h-1.921c-1.5 0-1.792.721-1.792 1.771v2.311h3.584l-.465 3.63H16.56V24h6.115c.733 0 1.325-.592 1.325-1.324V1.324C24 .593 23.408 0 22.676 0"></path>
        </svg>
    </a>
    @*<a href="https://twitter.com/intent/tweet?url=@enc&text=@text" target="_blank" rel="noopener noreferrer nofollow">
        <svg role="img" aria-labelledby="_tw">
            <title id="_tw">Share on Twitter</title>
            <path d="M23.954 4.569c-.885.389-1.83.654-2.825.775 1.014-.611 1.794-1.574 2.163-2.723-.951.555-2.005.959-3.127 1.184-.896-.959-2.173-1.559-3.591-1.559-2.717 0-4.92 2.203-4.92 4.917 0 .39.045.765.127 1.124C7.691 8.094 4.066 6.13 1.64 3.161c-.427.722-.666 1.561-.666 2.475 0 1.71.87 3.213 2.188 4.096-.807-.026-1.566-.248-2.228-.616v.061c0 2.385 1.693 4.374 3.946 4.827-.413.111-.849.171-1.296.171-.314 0-.615-.03-.916-.086.631 1.953 2.445 3.377 4.604 3.417-1.68 1.319-3.809 2.105-6.102 2.105-.39 0-.779-.023-1.17-.067 2.189 1.394 4.768 2.209 7.557 2.209 9.054 0 13.999-7.496 13.999-13.986 0-.209 0-.42-.015-.63.961-.689 1.8-1.56 2.46-2.548l-.047-.02z"></path>
        </svg>
    </a>
    <a href="https://plus.google.com/share?url=@enc" target="_blank" rel="noopener noreferrer nofollow">
        <svg role="img" aria-labelledby="_gp">
            <title id="_gp">Share on Google+</title>
            <path d="M7.635 10.909v2.619h4.335c-.173 1.125-1.31 3.295-4.331 3.295-2.604 0-4.731-2.16-4.731-4.823 0-2.662 2.122-4.822 4.728-4.822 1.485 0 2.479.633 3.045 1.178l2.073-1.994c-1.33-1.245-3.056-1.995-5.115-1.995C3.412 4.365 0 7.785 0 12s3.414 7.635 7.635 7.635c4.41 0 7.332-3.098 7.332-7.461 0-.501-.054-.885-.12-1.265H7.635zm16.365 0h-2.183V8.726h-2.183v2.183h-2.182v2.181h2.184v2.184h2.189V13.09H24"></path>
        </svg>
    </a>
    <a href="mailto:?subject=@Model.Replace(" ", "%20")&amp;body=@enc" target="_blank" rel="noopener noreferrer nofollow">
        <svg role="img" aria-labelledby="_em">
            <title id="_em">Email</title>
            <path d="M24 7.387v10.478c0 .23-.08.424-.238.576-.158.154-.352.23-.58.23h-8.547v-6.959l1.6 1.229c.102.085.229.126.379.126.148 0 .277-.041.389-.127L24 7.387zm-9.365-2.021h8.547c.211 0 .393.063.543.192.15.128.234.3.248.51l-7.369 5.876-1.969-1.549V5.366zM13.404.864v22.271L0 20.819V3.244L13.406.864h-.002zm-4.049 11.18c-.02-1.133-.313-2.072-.879-2.814-.555-.74-1.275-1.131-2.131-1.164-.824.033-1.529.423-2.1 1.164-.57.742-.855 1.682-.87 2.814.015 1.117.315 2.047.885 2.791.571.74 1.274 1.133 2.101 1.176.855-.035 1.574-.424 2.145-1.17.57-.748.87-1.68.885-2.797h-.036zm-3.12-2.482c.431.02.794.256 1.083.717.285.461.435 1.045.435 1.752 0 .721-.149 1.307-.435 1.771-.301.464-.66.704-1.096.704s-.795-.226-1.095-.69-.435-1.05-.435-1.754c0-.705.135-1.291.435-1.74.284-.45.646-.69 1.081-.721l.027-.039z"></path>
        </svg>
    </a>*@
</aside>