Areas/Dashboard/ViewModels/Sections/CreateSectionViewModel.cs
// -----------------------------------------------------------------------
//   Copyright (C) 2018 Adam Hancock
//    
//   CreateSectionViewModel.cs can not be copied and/or distributed without the express
//   permission of Adam Hancock
// -----------------------------------------------------------------------

namespace FlowerFest.Areas.Dashboard.ViewModels.Sections
{
    using System.ComponentModel.DataAnnotations;

    public class CreateSectionViewModel
    {
        public int Index { get; set; }

        [Required]
        public string Content { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Description { get; set; }

        public bool IsPublished { get; set; }

        public string Id { get; set; }
        
        public string Background { get; set; }

        public string Tag { get; set; }
    }
}

Areas/Dashboard/ViewModels/Sections/EditSectionViewModel.cs
// -----------------------------------------------------------------------
//   Copyright (C) 2018 Adam Hancock
//    
//   EditPostViewModel.cs can not be copied and/or distributed without the express
//   permission of Adam Hancock
// -----------------------------------------------------------------------

namespace FlowerFest.Areas.Dashboard.ViewModels.Sections
{
    using System.ComponentModel.DataAnnotations;

    public class EditSectionViewModel
    {
        public int Index { get; set; }

        [Required]
        public string Content { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Description { get; set; }

        public bool IsPublished { get; set; }
        
        public string Id { get; set; }
        
        public string Background { get; set; }

        public string Tag { get; set; }
    }
}

Areas/Dashboard/ViewModels/Sections/SectionViewModel.cs
// -----------------------------------------------------------------------
//   Copyright (C) 2018 Adam Hancock
//    
//   SectionViewModel.cs can not be copied and/or distributed without the express
//   permission of Adam Hancock
// -----------------------------------------------------------------------

namespace FlowerFest.Areas.Dashboard.ViewModels.Sections
{
    public class SectionViewModel
    {
        public string Id { get; set; }
        public int Index { get; set; }
        public string Tag { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}

ViewModels/Home/SectionViewModel.cs
// -----------------------------------------------------------------------
//   Copyright (C) 2018 Adam Hancock
//    
//   SectionViewModel.cs can not be copied and/or distributed without the express
//   permission of Adam Hancock
// -----------------------------------------------------------------------

namespace FlowerFest.ViewModels.Home
{
    public class SectionViewModel
    {
        public string Title { get; set; }
        public string Background { get; set; }
        public string Content { get; set; }
        public string Tag { get; set; }
    }
}

ViewModels/Shared/SectionViewModel.cs
// -----------------------------------------------------------------------
//   Copyright (C) 2018 Adam Hancock
//    
//   SectionViewModel.cs can not be copied and/or distributed without the express
//   permission of Adam Hancock
// -----------------------------------------------------------------------

namespace FlowerFest.ViewModels.Shared
{
    public class HeaderSectionViewModel
    {
        public string Tag { get; set; }
    }
}

Areas/Dashboard/Controllers/SectionsController.cs
// -----------------------------------------------------------------------
//   Copyright (C) 2018 Adam Hancock
//    
//   SectionsController.cs can not be copied and/or distributed without the express
//   permission of Adam Hancock
// -----------------------------------------------------------------------

namespace FlowerFest.Areas.Dashboard.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using AutoMapper;
    using DTO;
    using FlowerFest.Controllers;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;
    using Services.Interfaces;
    using ViewModels.Sections;

    [Area("Dashboard")]
    [Authorize]
    public class SectionsController : BaseController<SectionsController>
    {
        private readonly IMapper _mapper;
        private readonly ISectionService _service;

        public SectionsController(
            ISectionService service,
            IMapper mapper,
            ILogger<SectionsController> logger)
            : base(logger)
        {
            _service = service;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                return View("Index", _mapper.Map<IEnumerable<SectionViewModel>>(
                    await _service.GetSections()));
            }
            catch (Exception e)
            {
                return ServerError(e);
            }
        }

        public async Task<IActionResult> Create()
        {
            return View(new CreateSectionViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateSectionViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                if (await _service.CreateSection(_mapper.Map<Section>(model)))
                {
                    return RedirectToAction("Index");
                }

                return BadRequest();
            }
            catch (Exception e)
            {
                return ServerError(e);
            }
        }

        public async Task<IActionResult> Delete(string id = "")
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            try
            {
                if (await _service.DeleteSection(Guid.Parse(id)))
                {
                    return RedirectToAction("Index");
                }

                return NotFound();
            }
            catch (Exception e)
            {
                return ServerError(e);
            }
        }

        public async Task<IActionResult> Edit(string id = "")
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            try
            {
                var partner = await _service.GetSectionById(Guid.Parse(id));
                if (partner == null)
                {
                    return NotFound();
                }

                return View(_mapper.Map<EditSectionViewModel>(partner));
            }
            catch (Exception e)
            {
                return ServerError(e);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditSectionViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                if (await _service.UpdateSection(
                    _mapper.Map<Section>(model)))
                {
                    return RedirectToAction("Index");
                }

                return NotFound();
            }
            catch (Exception e)
            {
                return ServerError(e);
            }
        }
    }
}

Areas/Dashboard/Views/Sections/Create.cshtml
@model CreateSectionViewModel

@{
    Layout = "_Layout";
}

<div class="container">

    <h2>Create Section</h2>

    <form asp-controller="Sections" asp-action="Create" asp-area="Dashboard"
          emethod="post" enctype="multipart/form-data">
        
        <!-- Index -->
        <div class="row">
            <div class="standard-control col-md-12">
                <label asp-for="@Model.Index">Index</label>
                <div class="control">
                    <input class="form-control" type="number" asp-for="@Model.Index" placeholder="The order in which the section appears"/>
                    <span class="text-danger" asp-validation-for="@Model.Index"></span>
                </div>
            </div>
        </div>

        <!-- Tag -->
        <div class="row">
            <div class="standard-control col-md-12">
                <label asp-for="@Model.Tag">Tag</label>
                <div class="control">
                    <input class="form-control" asp-for="@Model.Tag" placeholder="The tag used for navigation" />
                    <span class="text-danger" asp-validation-for="@Model.Tag"></span>
                </div>
            </div>
        </div>

        <!-- Title -->
        <div class="row">
            <div class="standard-control col-md-12">
                <label asp-for="@Model.Title">Title</label>
                <div class="control">
                    <input class="form-control" asp-for="@Model.Title" placeholder="The title of the section"/>
                    <span class="text-danger" asp-validation-for="@Model.Title"></span>
                </div>
            </div>
        </div>

        <!-- Description -->
        <div class="row">
            <div class="standard-control col-md-12">
                <label asp-for="@Model.Description">Description</label>
                <div class="control">
                    <input class="form-control" asp-for="@Model.Description" placeholder="The description of the section"/>
                    <span class="text-danger" asp-validation-for="@Model.Description"></span>
                </div>
            </div>
        </div>

        <!-- Background -->
        <div class="row">
            <div class="standard-control col-md-12">
                <label asp-for="@Model.Background">Background</label>
                <div class="control">
                    <input class="form-control" asp-for="@Model.Background" placeholder="The background image for the section"/>
                    <span class="text-danger" asp-validation-for="@Model.Background"></span>
                </div>
            </div>
        </div>

        <!-- Content -->
        <div id="content" class="row">
            <div class="standard-control col-md-12">
                <label asp-for="@Model.Content">Content</label>
                <div class="control">
                    <textarea class="form-control" asp-for="@Model.Content" rows="20" autofocus placeholder="The content of the section"></textarea>
                    <span class="text-danger" asp-validation-for="@Model.Content"></span>
                </div>
            </div>
        </div>


        <div class="row justify-content-center">
            <div class="standard-control col-md-4">
                <input class="actions submit" type="submit" value="Save"/>
            </div>
        </div>

    </form>

</div>

Areas/Dashboard/Views/Sections/Edit.cshtml
@model EditSectionViewModel

@{
    Layout = "_Layout";
}

<div class="container">

    <h2>Edit Section</h2>

    <form asp-controller="Sections" asp-action="Edit" asp-area="Dashboard"
          emethod="post" enctype="multipart/form-data">

        <!-- Index -->
        <div class="row">
            <div class="standard-control col-md-12">
                <label asp-for="@Model.Index">Index</label>
                <div class="control">
                    <input class="form-control" type="number" asp-for="@Model.Index" placeholder="The order in which the section appears" />
                    <span class="text-danger" asp-validation-for="@Model.Index"></span>
                </div>
            </div>
        </div>

        <!-- Tag -->
        <div class="row">
            <div class="standard-control col-md-12">
                <label asp-for="@Model.Tag">Tag</label>
                <div class="control">
                    <input class="form-control" asp-for="@Model.Tag" placeholder="The tag used for navigation" />
                    <span class="text-danger" asp-validation-for="@Model.Tag"></span>
                </div>
            </div>
        </div>

        <!-- Title -->
        <div class="row">
            <div class="standard-control col-md-12">
                <label asp-for="@Model.Title">Title</label>
                <div class="control">
                    <input class="form-control" asp-for="@Model.Title" placeholder="The title of the section" />
                    <span class="text-danger" asp-validation-for="@Model.Title"></span>
                </div>
            </div>
        </div>

        <!-- Description -->
        <div class="row">
            <div class="standard-control col-md-12">
                <label asp-for="@Model.Description">Description</label>
                <div class="control">
                    <input class="form-control" asp-for="@Model.Description" placeholder="The description of the section" />
                    <span class="text-danger" asp-validation-for="@Model.Description"></span>
                </div>
            </div>
        </div>

        <!-- Background -->
        <div class="row">
            <div class="standard-control col-md-12">
                <label asp-for="@Model.Background">Background</label>
                <div class="control">
                    <input class="form-control" asp-for="@Model.Background" placeholder="The background image for the section" />
                    <span class="text-danger" asp-validation-for="@Model.Background"></span>
                </div>
            </div>
        </div>

        <!-- Content -->
        <div id="content" class="row">
            <div class="standard-control col-md-12">
                <label asp-for="@Model.Content">Content</label>
                <div class="control">
                    <textarea class="form-control" asp-for="@Model.Content" rows="20" autofocus placeholder="The content of the section"></textarea>
                    <span class="text-danger" asp-validation-for="@Model.Content"></span>
                </div>
            </div>
        </div>


        <div class="row justify-content-center">
            <div class="standard-control col-md-4">
                <input class="actions submit" type="submit" value="Save" />
            </div>
        </div>

    </form>

</div>

Areas/Dashboard/Views/Sections/Index.cshtml
@model IEnumerable<SectionViewModel>

@{
    ViewData["Title"] = "Sections";
}

<div class="container">
    
    <h2>Sections</h2>

    <p>
        <a asp-controller="Sections" asp-action="Create" asp-area="Dashboard">Create New</a>
    </p>

    <table class="table">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Index)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tag)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <label>@item.Index</label>
                </td>
                <td>
                    <label>@item.Tag</label>
                </td>
                <td>
                    <label>@item.Title</label>
                </td>
                <td>
                    <label>@item.Description</label>
                </td>
                <td>
                    <a asp-area="Dashboard" asp-controller="Sections" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-area="Dashboard" asp-controller="Sections" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>