Areas/Dashboard/ViewModels/Testimonials/CreateTestimonialViewModel.cs
// -----------------------------------------------------------------------
//   Copyright (C) 2018 Adam Hancock
//    
//   CreatePostViewModel.cs can not be copied and/or distributed without the express
//   permission of Adam Hancock
// -----------------------------------------------------------------------

namespace FlowerFest.Areas.Dashboard.ViewModels.Testimonials
{
    using System.ComponentModel.DataAnnotations;

    public class CreateTestimonialViewModel
    {
        public string Id { get; set; }
        [Required]
        public string Content { get; set; }
        [Required]
        public string Author { get; set; }
        [Required]
        public string Place { get; set; }
    }
}

Areas/Dashboard/ViewModels/Testimonials/EditTestimonialViewModel.cs
// -----------------------------------------------------------------------
//   Copyright (C) 2018 Adam Hancock
//    
//   EditPostViewModel.cs can not be copied and/or distributed without the express
//   permission of Adam Hancock
// -----------------------------------------------------------------------

namespace FlowerFest.Areas.Dashboard.ViewModels.Testimonials
{
    using System.ComponentModel.DataAnnotations;

    public class EditTestimonialViewModel
    {
        public string Id { get; set; }
        [Required]
        public string Content { get; set; }
        [Required]
        public string Author { get; set; }
        [Required]
        public string Place { get; set; }
    }
}

Areas/Dashboard/ViewModels/Testimonials/TestimonialViewModel.cs
// -----------------------------------------------------------------------
//   Copyright (C) 2018 Adam Hancock
//    
//   TestimonialViewModel.cs can not be copied and/or distributed without the express
//   permission of Adam Hancock
// -----------------------------------------------------------------------

namespace FlowerFest.Areas.Dashboard.ViewModels.Testimonials
{
    public class TestimonialViewModel
    {
        public string Id { get; set; }
        public string Content { get; set; }
        public string Author { get; set; }
        public string Place { get; set; }
    }
}

ViewModels/Home/TestimonialViewModel.cs
// -----------------------------------------------------------------------
//   Copyright (C) 2018 Adam Hancock
//    
//   TestimonialViewModel.cs can not be copied and/or distributed without the express
//   permission of Adam Hancock
// -----------------------------------------------------------------------

namespace FlowerFest.ViewModels.Home
{
    using System;

    public class TestimonialViewModel
    {
        public Guid Id { get; set; }

        public string Content { get; set; }
        public string Author { get; set; }
        public string Place { get; set; }
    }
}

Areas/Dashboard/Controllers/TestimonialsController.cs
// -----------------------------------------------------------------------
//   Copyright (C) 2018 Adam Hancock
//    
//   TestimonialsController.cs can not be copied and/or distributed without the express
//   permission of Adam Hancock
// -----------------------------------------------------------------------

namespace FlowerFest.Areas.Dashboard.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using AutoMapper;
    using DTO;
    using FlowerFest.Controllers;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;
    using Services.Interfaces;
    using ViewModels.Testimonials;

    [Area("Dashboard")]
    [Authorize]
    public class TestimonialsController : BaseController<TestimonialsController>
    {
        private readonly IMapper _mapper;
        private readonly ITestimonalService _service;

        public TestimonialsController(
            ITestimonalService service,
            IMapper mapper,
            ILogger<TestimonialsController> logger)
            : base(logger)
        {
            _service = service;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                return View(_mapper.Map<IEnumerable<TestimonialViewModel>>(
                    await _service.GetTestimonials()));
            }
            catch (Exception e)
            {
                return ServerError(e);
            }
        }

        public async Task<IActionResult> Create()
        {
            return View(new CreateTestimonialViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateTestimonialViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                if (await _service.CreateTestimonial(_mapper.Map<Testimonial>(model)))
                {
                    return RedirectToAction("Index");
                }

                return BadRequest();
            }
            catch (Exception e)
            {
                return ServerError(e);
            }
        }
        
        public async Task<IActionResult> Delete(string id = "")
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            try
            {
                if (await _service.DeleteTestimonial(Guid.Parse(id)))
                {
                    return RedirectToAction("Index");
                }

                return NotFound();
            }
            catch (Exception e)
            {
                return ServerError(e);
            }
        }

        public async Task<IActionResult> Edit(string id = "")
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            try
            {
                var partner = await _service.GetTestimonialById(Guid.Parse(id));
                if (partner == null)
                {
                    return NotFound();
                }

                return View(_mapper.Map<EditTestimonialViewModel>(partner));
            }
            catch (Exception e)
            {
                return ServerError(e);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditTestimonialViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                if (await _service.UpdateTestimonial(
                    _mapper.Map<Testimonial>(model)))
                {
                    return RedirectToAction("Index");
                }

                return NotFound();

            }
            catch (Exception e)
            {
                return ServerError(e);
            }
        }
    }
}

Areas/Dashboard/Views/Testimonials/Create.cshtml
@model CreateTestimonialViewModel

@{
    Layout = "_Layout";
}

<div class="container">

    <h2>Create Testimonial</h2>

    <form asp-controller="Testimonials" asp-action="Create" asp-area="Dashboard"
          emethod="post" enctype="multipart/form-data">

        <!-- Author -->
        <div class="row">
            <div class="standard-control col-md-12">
                <label asp-for="@Model.Author">Author</label>
                <div class="control">
                    <input class="form-control" asp-for="@Model.Author" placeholder="The person who made the statement" />
                    <span class="text-danger" asp-validation-for="@Model.Author"></span>
                </div>
            </div>
        </div>

        <!-- Place -->
        <div class="row">
            <div class="standard-control col-md-12">
                <label asp-for="@Model.Place">Place</label>
                <div class="control">
                    <input class="form-control" asp-for="@Model.Place" placeholder="The company at which the person works" />
                    <span class="text-danger" asp-validation-for="@Model.Place"></span>
                </div>
            </div>
        </div>
        
        <!-- Content -->
        <div id="content" class="row">
            <div class="standard-control col-md-12">
                <label asp-for="@Model.Content">Content</label>
                <div class="control">
                    <textarea class="form-control" asp-for="@Model.Content" rows="20" autofocus placeholder="The content of the section"></textarea>
                    <span class="text-danger" asp-validation-for="@Model.Content"></span>
                </div>
            </div>
        </div>


        <div class="row justify-content-center">
            <div class="standard-control col-md-4">
                <input class="actions submit" type="submit" value="Save" />
            </div>
        </div>

    </form>

</div>

Areas/Dashboard/Views/Testimonials/Edit.cshtml
@model EditTestimonialViewModel

@{
    Layout = "_Layout";
}

<div class="container">

    <h2>Edit Testimonial</h2>

    <form asp-controller="Testimonials" asp-action="Edit" asp-area="Dashboard"
          emethod="post" enctype="multipart/form-data">

        <!-- Author -->
        <div class="row">
            <div class="standard-control col-md-12">
                <label asp-for="@Model.Author">Author</label>
                <div class="control">
                    <input class="form-control" asp-for="@Model.Author" placeholder="The person who made the statement" />
                    <span class="text-danger" asp-validation-for="@Model.Author"></span>
                </div>
            </div>
        </div>

        <!-- Place -->
        <div class="row">
            <div class="standard-control col-md-12">
                <label asp-for="@Model.Place">Place</label>
                <div class="control">
                    <input class="form-control" asp-for="@Model.Place" placeholder="The company at which the person works" />
                    <span class="text-danger" asp-validation-for="@Model.Place"></span>
                </div>
            </div>
        </div>

        <!-- Content -->
        <div id="content" class="row">
            <div class="standard-control col-md-12">
                <label asp-for="@Model.Content">Content</label>
                <div class="control">
                    <textarea class="form-control" asp-for="@Model.Content" rows="20" autofocus placeholder="The content of the section"></textarea>
                    <span class="text-danger" asp-validation-for="@Model.Content"></span>
                </div>
            </div>
        </div>


        <div class="row justify-content-center">
            <div class="standard-control col-md-4">
                <input class="actions submit" type="submit" value="Save" />
            </div>
        </div>

    </form>

</div>

Areas/Dashboard/Views/Testimonials/Index.cshtml
@model IEnumerable<TestimonialViewModel>

@{
    ViewData["Title"] = "Testimonials";
}

<div class="container">


    <h2>Testimonials</h2>

    <p>
        <a asp-controller="Testimonials" asp-action="Create" asp-area="Dashboard">Create New</a>
    </p>

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Content)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Author)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Place)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <label>@item.Content</label>
            </td>
            <td>
                <label>@item.Author</label>
            </td>
            <td>
                <label>@item.Place</label>
            </td>
            <td>
                <a asp-area="Dashboard" asp-controller="Testimonials" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-area="Dashboard" asp-controller="Testimonials" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
            }
        </tbody>
    </table>
</div>